name: build

on:
  push:
    branches:
      - main
      - xuxiaowei/*
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 25 ]
        os:
          - macos-26-intel
          - macos-26
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install musl toolchain (Linux static build)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-dev musl-tools

      - name: Set up JDK ${{ matrix.java-version }}
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Cache modules
        uses: actions/cache@v5
        id: cache-modules
        with:
          path: |
            ~/.m2/repository
          key: ${{ matrix.os }}-${{ hashFiles('pom.xml', '**/pom.xml', '**/**/pom.xml', '**/package.json') }}
          restore-keys: |
            ${{ matrix.os }}-

      - name: Maven Version
        run: mvn -v

      - name: Get Artifact ID
        id: get-artifact-id
        run: echo "ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
        shell: bash

      - name: Get Version
        id: get-version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        shell: bash

      - name: Maven native Build
        run: mvn -V -B clean package -Pnative native:compile "-DimageName=${{ env.ARTIFACT_ID }}-${{ runner.os }}-${{ runner.arch }}"

      - name: Upload native artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT_ID }}-${{ runner.os }}-${{ runner.arch }}
          path: |
            target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}-*
            !target/*.jar
