name: build

on:
  push:
    branches:
      - main
      - xuxiaowei/*

jobs:
  build:
    name: build
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        java-version: [ 25 ]
        runner:
          - macos-13
          - macos-latest
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
        include:
          - runner: macos-13
            os: macos
            arch: x86_64
          - runner: macos-latest
            os: macos
            arch: arm64
          - runner: ubuntu-latest
            os: linux
            arch: x86_64
          - runner: ubuntu-24.04-arm
            os: linux
            arch: arm64
          - runner: windows-latest
            os: windows
            arch: x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'

      - name: Maven Version
        run: mvn -v
