name: build

on:
  push:
    branches:
      - main
      - xuxiaowei/*

jobs:
  build:
    name: build
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        java-version: [ 25 ]
        runner:
          - macos-26-intel
          - macos-latest
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'

      - name: Maven Version
        run: mvn -v
